spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KIRIN_RESERVE
    username: KIRIN_DEV
    password: ${MYSQL_PASSWORD}

server:
  port: ${APP_PORT}

line:
  bot:
    channel-token: ${LINE_BOT_CHANNEL_TOKEN}
    # channel-secret: ${LINE_BOT_CHANNEL_SECRET} いらない説あり
    group-id: ${LINE_BOT_GROUP_ID}

kirin:
  user: ${KIRIN_USER}
  password: ${KIRIN_PASSWORD}
  url: ${KIRIN_URL}
  start-time_am: ${KIRIN_START_TIME_AM}
  start-time_pm: ${KIRIN_START_TIME_PM}

selenium:
  host: ${SELENIUM_HOST}

cron: ${CRON}
