name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  test:
    uses: ./.github/workflows/maven-test.yml
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v3
    - name: Execute ssh
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        port: ${{secrets.SSH_PORT}}
        script: |
          cd ~/repository/kirin-reservation-batch
          git pull origin master
          mvn -B package -DskipTests --file pom.xml
          cd ~/repository/kirin-reservation-batch/target
          cp reservation-batch.jar reservation-batch-nao.jar 
          cp reservation-batch.jar reservation-batch-kyo.jar 
          systemctl --user restart kirin-reservation-batch-nao
          systemctl --user restart kirin-reservation-batch-kyo
          
          
            
